// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/proto/article_service.proto

package article

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- request & response
type ProcessArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticlesRequest) Reset() {
	*x = ProcessArticlesRequest{}
	mi := &file_internal_proto_article_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesRequest) ProtoMessage() {}

func (x *ProcessArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesRequest.ProtoReflect.Descriptor instead.
func (*ProcessArticlesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessArticlesRequest) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type ProcessArticlesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalProcessed int32                  `protobuf:"varint,1,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessArticlesResponse) Reset() {
	*x = ProcessArticlesResponse{}
	mi := &file_internal_proto_article_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesResponse) ProtoMessage() {}

func (x *ProcessArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesResponse.ProtoReflect.Descriptor instead.
func (*ProcessArticlesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessArticlesResponse) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

type GetTopTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsRequest) Reset() {
	*x = GetTopTagsRequest{}
	mi := &file_internal_proto_article_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsRequest) ProtoMessage() {}

func (x *GetTopTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTopTagsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagFrequency        `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsResponse) Reset() {
	*x = GetTopTagsResponse{}
	mi := &file_internal_proto_article_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsResponse) ProtoMessage() {}

func (x *GetTopTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTopTagsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopTagsResponse) GetTags() []*TagFrequency {
	if x != nil {
		return x.Tags
	}
	return nil
}

// --- data models
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_internal_proto_article_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{4}
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TagFrequency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Frequency     int32                  `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagFrequency) Reset() {
	*x = TagFrequency{}
	mi := &file_internal_proto_article_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagFrequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFrequency) ProtoMessage() {}

func (x *TagFrequency) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_article_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFrequency.ProtoReflect.Descriptor instead.
func (*TagFrequency) Descriptor() ([]byte, []int) {
	return file_internal_proto_article_service_proto_rawDescGZIP(), []int{5}
}

func (x *TagFrequency) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagFrequency) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

var File_internal_proto_article_service_proto protoreflect.FileDescriptor

const file_internal_proto_article_service_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/article_service.proto\x12\aarticle\"F\n" +
	"\x16ProcessArticlesRequest\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\"B\n" +
	"\x17ProcessArticlesResponse\x12'\n" +
	"\x0ftotal_processed\x18\x01 \x01(\x05R\x0etotalProcessed\")\n" +
	"\x11GetTopTagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"?\n" +
	"\x12GetTopTagsResponse\x12)\n" +
	"\x04tags\x18\x01 \x03(\v2\x15.article.TagFrequencyR\x04tags\"3\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\">\n" +
	"\fTagFrequency\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x05R\tfrequency2\xad\x01\n" +
	"\x0eArticleService\x12T\n" +
	"\x0fProcessArticles\x12\x1f.article.ProcessArticlesRequest\x1a .article.ProcessArticlesResponse\x12E\n" +
	"\n" +
	"GetTopTags\x12\x1a.article.GetTopTagsRequest\x1a\x1b.article.GetTopTagsResponseB\fZ\n" +
	"./;articleb\x06proto3"

var (
	file_internal_proto_article_service_proto_rawDescOnce sync.Once
	file_internal_proto_article_service_proto_rawDescData []byte
)

func file_internal_proto_article_service_proto_rawDescGZIP() []byte {
	file_internal_proto_article_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_article_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_article_service_proto_rawDesc), len(file_internal_proto_article_service_proto_rawDesc)))
	})
	return file_internal_proto_article_service_proto_rawDescData
}

var file_internal_proto_article_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_article_service_proto_goTypes = []any{
	(*ProcessArticlesRequest)(nil),  // 0: article.ProcessArticlesRequest
	(*ProcessArticlesResponse)(nil), // 1: article.ProcessArticlesResponse
	(*GetTopTagsRequest)(nil),       // 2: article.GetTopTagsRequest
	(*GetTopTagsResponse)(nil),      // 3: article.GetTopTagsResponse
	(*Article)(nil),                 // 4: article.Article
	(*TagFrequency)(nil),            // 5: article.TagFrequency
}
var file_internal_proto_article_service_proto_depIdxs = []int32{
	4, // 0: article.ProcessArticlesRequest.articles:type_name -> article.Article
	5, // 1: article.GetTopTagsResponse.tags:type_name -> article.TagFrequency
	0, // 2: article.ArticleService.ProcessArticles:input_type -> article.ProcessArticlesRequest
	2, // 3: article.ArticleService.GetTopTags:input_type -> article.GetTopTagsRequest
	1, // 4: article.ArticleService.ProcessArticles:output_type -> article.ProcessArticlesResponse
	3, // 5: article.ArticleService.GetTopTags:output_type -> article.GetTopTagsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_article_service_proto_init() }
func file_internal_proto_article_service_proto_init() {
	if File_internal_proto_article_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_article_service_proto_rawDesc), len(file_internal_proto_article_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_article_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_article_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_article_service_proto_msgTypes,
	}.Build()
	File_internal_proto_article_service_proto = out.File
	file_internal_proto_article_service_proto_goTypes = nil
	file_internal_proto_article_service_proto_depIdxs = nil
}
