services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: article-tag-extractor
    ports:
      - "50051:50051"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB_NAME: article_db
      GRPC_SERVER_PORT: 50051
    restart: unless-stopped
    depends_on:
      - mongo

volumes:
  mongo-data: 
