services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  
  app:
    build: .
    container_name: article-tag-extractor
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
      MONGO_DB_NAME: article_db
      GRPC_SERVER_PORT: 50051
    depends_on:
      - mongo

volumes:
  mongo-data: 
